.TH ODYNSTOCK-CLI "1" "February 2016" "odynstock-cli 0.12"
.SH NAME
odynstock-cli \- a remote procedure call client for OdynStock Core. 
.SH SYNOPSIS
odynstock-cli [options] <command> [params] \- Send command to OdynStock Core. 
.TP
odynstock-cli [options] help \- Asks OdynStock Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the odynstock-cli program. odynstock-cli is an RPC client used to send commands to OdynStock Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBodynstockd\fP, \fBodynstock.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
